import type { Contact, CustomField, GrafyState, Group } from "./types";

const timestamp = "2026-05-28T12:00:00.000Z";

export const seedContacts: Contact[] = [
  {
    id: "ct_ana",
    name: "Ana Beatriz Costa",
    headline: "CEO da TechFlow",
    description: "Executiva focada em transformação digital para empresas tradicionais.",
    tags: ["tecnologia", "CEO", "diretor", "diretoria", "decisor", "inovação", "São Paulo", "B2B", "produto digital"],
    phones: ["11987654321"],
    emails: ["ana@techflow.com.br"],
    ddd: "11",
    source: "Google Contacts",
    currentDemand: "Busca CTO para nova operação de produtos digitais.",
    problemSolves: "Ajuda empresas tradicionais a implantarem estratégia digital e cultura de inovação.",
    notes: "Conhecida em evento de tecnologia. Tem interesse em comunidade de founders.",
    links: [
      { kind: "whatsapp", value: "11987654321" },
      { kind: "linkedin", value: "anabeatrizcosta" }
    ],
    isPublic: true,
    linkedUserId: "usr_ana",
    groupIds: ["grp_founders"],
    customFields: { ticketMedio: "enterprise", prioridade: "alta", area: "tecnologia", cargo: "CEO", tipoNegocio: "SaaS B2B" },
    lastInteractionAt: "2026-05-20",
    nextFollowUpAt: "2026-06-04",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "ct_carlos",
    name: "Carlos Eduardo Silva",
    headline: "Investidor anjo e mentor SaaS",
    description: "Investidor com foco em SaaS B2B, vendas consultivas e go-to-market.",
    tags: ["investidor", "mentor", "SaaS", "startups", "finanças", "diretor", "decisor", "diretoria", "B2B", "fundraising"],
    phones: ["21976543210"],
    emails: ["carlos@investsmart.com"],
    ddd: "21",
    source: "CSV",
    currentDemand: "Procura startups early-stage para investir.",
    problemSolves: "Mentoria, fundraising e desenho de máquina de vendas B2B.",
    notes: "Bom contato para apresentar founders com tração inicial.",
    links: [{ kind: "linkedin", value: "carloseduardosilva" }],
    isPublic: false,
    groupIds: ["grp_founders"],
    customFields: { ticketMedio: "seed", prioridade: "média", area: "investimentos", cargo: "Investidor", tipoNegocio: "Venture" },
    lastInteractionAt: "2026-05-12",
    nextFollowUpAt: "2026-06-10",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "ct_marina",
    name: "Marina Torres",
    headline: "Especialista em marketing de comunidades",
    description: "Construiu comunidades para edtechs, eventos e marcas B2B.",
    tags: ["marketing", "comunidade", "eventos", "conteúdo", "growth", "parcerias", "B2B", "comunicação"],
    phones: ["31988887777"],
    emails: ["marina@communitylab.com"],
    ddd: "31",
    source: "Manual",
    currentDemand: "Busca parcerias com hubs de inovação e eventos empresariais.",
    problemSolves: "Cria comunidades, conteúdo e campanhas para ativação de networking.",
    notes: "Pode ajudar na estratégia de lançamento do Grafy.",
    links: [
      { kind: "instagram", value: "marinatorres.mkt" },
      { kind: "linkedin", value: "marinatorres" }
    ],
    isPublic: true,
    linkedUserId: "usr_marina",
    groupIds: ["grp_eventos"],
    customFields: { ticketMedio: "médio", prioridade: "alta", area: "marketing", cargo: "Especialista", tipoNegocio: "Comunidade" },
    lastInteractionAt: "2026-05-25",
    nextFollowUpAt: "2026-06-02",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "ct_bruno",
    name: "Bruno Mendes",
    headline: "Recrutador tech",
    description: "Especialista em contratar devs, CTOs e lideranças técnicas.",
    tags: ["RH", "recrutamento", "tecnologia", "CTO", "diretor", "diretoria", "decisor", "talentos", "liderança"],
    phones: ["11999998888"],
    emails: ["bruno@talentforge.com"],
    ddd: "11",
    source: "Google Contacts",
    currentDemand: "Busca empresas em crescimento que precisam montar time técnico.",
    problemSolves: "Recrutamento tech para CTO, engenharia, dados e produto.",
    notes: "Potencial match com Ana por demanda de CTO.",
    links: [{ kind: "linkedin", value: "brunomendes-tech" }],
    isPublic: false,
    groupIds: ["grp_founders"],
    customFields: { ticketMedio: "médio", prioridade: "alta", area: "RH", cargo: "Recrutador", tipoNegocio: "Serviços B2B" },
    lastInteractionAt: "2026-05-22",
    nextFollowUpAt: "2026-06-01",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "ct_luiza",
    name: "Luiza Carvalho",
    headline: "Consultora financeira para PMEs",
    description: "Organiza fluxo de caixa, precificação e planejamento financeiro.",
    tags: ["finanças", "PME", "consultoria", "gestão", "CFO", "diretor", "diretoria", "decisor", "B2B"],
    phones: ["41977776666"],
    emails: ["luiza@finpme.com.br"],
    ddd: "41",
    source: "CSV",
    currentDemand: "Procura empresários com operação crescendo e baixa previsibilidade financeira.",
    problemSolves: "Estrutura financeiro, indicadores e rituais de gestão para PMEs.",
    notes: "Boa para grupos de empresários locais.",
    links: [{ kind: "url", value: "https://finpme.com.br" }],
    isPublic: true,
    linkedUserId: "usr_luiza",
    groupIds: ["grp_empresarios"],
    customFields: { ticketMedio: "médio", prioridade: "média", area: "finanças", cargo: "Consultora", tipoNegocio: "PME" },
    lastInteractionAt: "2026-04-30",
    nextFollowUpAt: "2026-06-08",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "ct_rafael",
    name: "Rafael Nunes",
    headline: "Especialista em limpeza empresarial",
    description: "Opera equipes de limpeza para escritórios, eventos e condomínios comerciais.",
    tags: ["limpeza", "operações", "facilities", "eventos", "fornecedores", "B2B", "contratos recorrentes"],
    phones: ["61987651234"],
    emails: ["rafael@limpabrasil.com"],
    ddd: "61",
    source: "Manual",
    currentDemand: "Busca contratos recorrentes com escritórios e eventos.",
    problemSolves: "Serviços de limpeza e facilities com equipe treinada e contrato recorrente.",
    notes: "Exemplo bom para perguntas do chat sobre serviço de limpeza.",
    links: [{ kind: "whatsapp", value: "61987651234" }],
    isPublic: false,
    groupIds: ["grp_eventos"],
    customFields: { ticketMedio: "baixo", prioridade: "média", area: "operações", cargo: "Fornecedor", tipoNegocio: "Serviços locais" },
    lastInteractionAt: "2026-05-01",
    nextFollowUpAt: "2026-05-30",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "ct_helena",
    name: "Helena Arantes",
    headline: "Diretora de experiência na Casa Nexo Eventos",
    description: "Coordena eventos corporativos, curadoria de patrocinadores e experiência de convidados para marcas B2B.",
    tags: ["eventos", "patrocínio", "experiência", "corporativo", "São Paulo", "diretor", "diretoria", "decisor", "marketing", "B2B"],
    phones: ["11955667788"],
    emails: ["helena@casanexo.com.br"],
    ddd: "11",
    source: "Google Contacts",
    currentDemand: "Procura fornecedores premium para eventos executivos e comunidades de líderes.",
    problemSolves: "Desenha experiências presenciais com patrocinadores, ativa comunidade e mede relacionamento pós-evento.",
    notes: "Conhecida no jantar de lideranças da Vila Olímpia em 18/05. Boa ponte para Meetup/GraphQL de eventos.",
    links: [
      { kind: "linkedin", value: "helenaarantes-eventos" },
      { kind: "instagram", value: "casanexo.eventos" }
    ],
    isPublic: true,
    linkedUserId: "usr_helena",
    groupIds: ["grp_eventos", "grp_empresarios"],
    customFields: { ticketMedio: "enterprise", prioridade: "alta", area: "eventos", cargo: "Diretora", tipoNegocio: "Eventos B2B" },
    lastInteractionAt: "2026-05-18",
    nextFollowUpAt: "2026-06-03",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "ct_thiago",
    name: "Thiago Pacheco",
    headline: "Consultor de cibersegurança para scale-ups",
    description: "Implanta governança, segurança em cloud e treinamentos para empresas em crescimento.",
    tags: ["segurança", "cloud", "SaaS", "compliance", "CTO", "diretor", "tecnologia", "diretoria", "risco"],
    phones: ["21988771122"],
    emails: ["thiago@shieldops.com.br"],
    ddd: "21",
    source: "Rede Pública",
    currentDemand: "Busca parcerias com consultorias de tecnologia e comunidades de founders.",
    problemSolves: "Reduz risco operacional, prepara auditorias e cria trilhas práticas de segurança para times técnicos.",
    notes: "Perfil público descoberto pela rede. Potencial apresentação para Ana e Bruno.",
    links: [{ kind: "linkedin", value: "thiagopacheco-security" }],
    isPublic: true,
    linkedUserId: "usr_thiago",
    groupIds: ["grp_founders"],
    customFields: { ticketMedio: "enterprise", prioridade: "média", area: "tecnologia", cargo: "Consultor", tipoNegocio: "Scale-up" },
    lastInteractionAt: "2026-05-23",
    nextFollowUpAt: "2026-06-07",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "ct_gabriela",
    name: "Gabriela Lobo",
    headline: "Head de Customer Success em healthtech",
    description: "Escala operações de sucesso do cliente, onboarding e expansão em vendas B2B de alto contato.",
    tags: ["customer success", "SaaS", "healthtech", "operações", "expansão", "head", "decisor", "B2B"],
    phones: ["31992224455"],
    emails: ["gabriela@cuidare.ai"],
    ddd: "31",
    source: "Manual",
    currentDemand: "Quer trocar experiências com líderes que reduziram churn em vendas consultivas.",
    problemSolves: "Estrutura playbooks de onboarding, QBRs, expansão e indicadores de saúde de carteira.",
    notes: "Indicada pela Marina para painel de comunidade. Boa conversa para produto B2B.",
    links: [{ kind: "linkedin", value: "gabrielalobo-cs" }],
    isPublic: false,
    groupIds: ["grp_founders", "grp_eventos"],
    customFields: { ticketMedio: "médio", prioridade: "alta", area: "operações", cargo: "Head", tipoNegocio: "Healthtech" },
    lastInteractionAt: "2026-05-24",
    nextFollowUpAt: "2026-06-06",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "ct_davi",
    name: "Davi Coutinho",
    headline: "Founder da ObraClara, tecnologia para construtoras",
    description: "Construiu uma plataforma para controle de obras, compras e fornecedores regionais.",
    tags: ["construção", "PME", "SaaS", "fornecedores", "Recife", "founder", "decisor", "B2B"],
    phones: ["81984445566"],
    emails: ["davi@obraclara.com"],
    ddd: "81",
    source: "CSV",
    currentDemand: "Procura investidores e canais com construtoras de médio porte.",
    problemSolves: "Ajuda construtoras a controlar custos, prazos, compras e comunicação com fornecedores.",
    notes: "Importado de lista de evento no Recife. Pode combinar com Carlos e Luiza.",
    links: [
      { kind: "linkedin", value: "davicoutinho-obraclara" },
      { kind: "url", value: "https://obraclara.com" }
    ],
    isPublic: false,
    groupIds: ["grp_founders", "grp_empresarios"],
    customFields: { ticketMedio: "seed", prioridade: "média", area: "construção", cargo: "Founder", tipoNegocio: "SaaS vertical" },
    lastInteractionAt: "2026-05-16",
    nextFollowUpAt: "2026-06-11",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "ct_julia",
    name: "Julia Ramos",
    headline: "Advogada societária",
    description: "Atua em contratos, acordos de sócios e estruturação para startups.",
    tags: ["jurídico", "contratos", "startups", "societário", "compliance", "B2B", "consultoria"],
    phones: ["11981234567"],
    emails: ["julia@ramoslegal.com"],
    ddd: "11",
    source: "Rede Pública",
    currentDemand: "Quer se conectar com founders em fase de captação.",
    problemSolves: "Contratos, governança e acordos de sócios para empresas em crescimento.",
    notes: "Perfil público importado para demonstrar vínculo externo.",
    links: [{ kind: "linkedin", value: "juliaramoslegal" }],
    isPublic: true,
    linkedUserId: "usr_julia",
    groupIds: [],
    customFields: { ticketMedio: "médio", prioridade: "baixa", area: "jurídico", cargo: "Especialista", tipoNegocio: "Serviços B2B" },
    lastInteractionAt: "2026-05-18",
    nextFollowUpAt: "2026-06-12",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "ct_ana_dup",
    name: "Ana B. Costa",
    headline: "Transformação digital",
    description: "Contato duplicado vindo de planilha de evento.",
    tags: ["tecnologia", "evento", "diretoria", "decisor"],
    phones: ["11 98765-4321"],
    emails: ["ana@techflow.com.br"],
    ddd: "11",
    source: "CSV",
    currentDemand: "Busca liderança técnica.",
    problemSolves: "Transformação digital.",
    notes: "Duplicado proposital para validar merge.",
    links: [],
    isPublic: false,
    groupIds: ["grp_eventos"],
    customFields: { ticketMedio: "enterprise", prioridade: "alta", area: "tecnologia", cargo: "CEO", tipoNegocio: "SaaS B2B" },
    lastInteractionAt: "2026-05-17",
    nextFollowUpAt: "2026-06-05",
    createdAt: timestamp,
    updatedAt: timestamp
  }
];

export const seedGroups: Group[] = [
  {
    id: "grp_founders",
    name: "Founders e Investidores",
    description: "Grupo para conectar founders, investidores e especialistas de crescimento.",
    role: "admin",
    color: "#66e7ff",
    members: ["lenin@grafy.local", "ana@techflow.com.br", "carlos@investsmart.com", "thiago@shieldops.com.br"],
    contactIds: ["ct_ana", "ct_carlos", "ct_bruno", "ct_thiago", "ct_gabriela", "ct_davi"],
    tags: ["startups", "investimento", "tecnologia", "decisores"],
    createdAt: timestamp
  },
  {
    id: "grp_eventos",
    name: "Networking de Eventos",
    description: "Rede compartilhada para fornecedores, palestrantes e organizadores.",
    role: "admin",
    color: "#a993ff",
    members: ["lenin@grafy.local", "marina@communitylab.com", "helena@casanexo.com.br"],
    contactIds: ["ct_marina", "ct_rafael", "ct_ana_dup", "ct_helena", "ct_gabriela"],
    tags: ["eventos", "comunidade", "fornecedores", "marketing"],
    createdAt: timestamp
  },
  {
    id: "grp_empresarios",
    name: "Empresários Regionais",
    description: "Comunidade fechada para empresários e prestadores B2B.",
    role: "member",
    color: "#ffd166",
    members: ["lenin@grafy.local", "luiza@finpme.com.br", "davi@obraclara.com"],
    contactIds: ["ct_luiza", "ct_davi", "ct_helena"],
    tags: ["PME", "gestão", "negócios", "finanças"],
    createdAt: timestamp
  }
];

export const seedCustomFields: CustomField[] = [
  {
    id: "cf_priority",
    scope: "user",
    name: "Prioridade",
    key: "prioridade",
    type: "select",
    options: ["alta", "média", "baixa"],
    isFilterable: true
  },
  {
    id: "cf_ticket",
    scope: "user",
    name: "Ticket médio",
    key: "ticketMedio",
    type: "select",
    options: ["baixo", "médio", "enterprise", "seed"],
    isFilterable: true
  }
];

export const initialState: GrafyState = {
  schemaVersion: "ux-neural-2026-05-28",
  profile: {
    id: "usr_lenin",
    name: "Leninn Rodrigues",
    headline: "Conector de negócios e IA aplicada",
    description: "Uso o Grafy para mapear contatos, oportunidades e comunidades de networking.",
    tags: ["networking", "IA", "negócios", "comunidades", "parcerias"],
    problemSolves: "Conecta pessoas, organiza oportunidades e transforma ideias em protótipos funcionais.",
    currentDemand: "Busco parceiros para validar o Grafy em comunidades empresariais.",
    visibility: "private",
    links: [
      { kind: "linkedin", value: "leninn-rodrigues" },
      { kind: "url", value: "https://grafyy.lovable.app" }
    ]
  },
  contacts: seedContacts,
  groups: seedGroups,
  customFields: seedCustomFields,
  chatMessages: [
    {
      id: "msg_welcome",
      role: "assistant",
      content: "Pergunte por demandas, problemas resolvidos, DDDs, tags ou duplicados. Eu busco na sua rede e devolvo contatos acionáveis.",
      createdAt: timestamp
    }
  ],
  completedOnboarding: true
};
